name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build with Maven
        run: mvn package

      - name: Move jar file to dist directory
        run: mv target/*.jar .github/dist/

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          body: |
            Changes in this Release:
            - add some changes here
          draft: false
          prerelease: false

      - name: Upload jar asset
        id: upload-jar
        uses: actions/upload-artifact@v2
        with:
          name: jar
          path: .github/dist/*.jar

      - name: Attach jar asset to Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          body: |
            Changes in this Release:
            - add some changes here
          draft: false
          prerelease: false
          files: |
            ${{ steps.upload-jar.outputs.artifact_path }}