name: Build and Release

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Install JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Install Postgres as dependency to run tests
        run: |
          docker run --name="pg" -u=postgres -e POSTGRES_PASSWORD="pg" -d --net=host cgr.dev/chainguard/postgres:latest
          sleep 5
          docker cp ./database/schema.sql pg:/home/postgres
          docker cp ./database/trigger.sql pg:/home/postgres
          docker cp ./database/data_base.sql pg:/home/postgres
          docker cp ./database/data_many.sql pg:/home/postgres
          docker exec pg psql -U postgres -f /home/postgres/schema.sql
          docker exec pg psql -U postgres -f /home/postgres/trigger.sql
          docker exec pg psql -U postgres -f /home/postgres/data_base.sql
          docker exec pg psql -U postgres -f /home/postgres/data_many.sql    

      - name: Run tests and build with Maven if successful
        working-directory: ./backend
        run: mvn -B package --file pom.xml

      - name: Connect to AWS and copy the application
        working-directory: ./backend
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.AWS_KNOWN_HOSTS }}
        run: |
          pwd
          ls -la ../
          mkdir -p ~/.ssh/
          printf %s\\n "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          printf %s\\n "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/id_rsa
          chmod 644 ~/.ssh/known_hosts
          ssh    -i ~/.ssh/id_rsa ubuntu@ec2-52-221-189-102.ap-southeast-1.compute.amazonaws.com "printf \"%s\\n\" \"Actual write test: $(date)\" >> /home/ubuntu/ctbs/testfile.txt"
          scp    -i ~/.ssh/id_rsa target/backend-1.0.0-SNAPSHOT.jar ubuntu@ec2-52-221-189-102.ap-southeast-1.compute.amazonaws.com:/home/ubuntu/ctbs
          scp    -i ~/.ssh/id_rsa ../database/schema.sql ubuntu@ec2-52-221-189-102.ap-southeast-1.compute.amazonaws.com:/home/ubuntu/ctbs
          scp    -i ~/.ssh/id_rsa ../database/trigger.sql ubuntu@ec2-52-221-189-102.ap-southeast-1.compute.amazonaws.com:/home/ubuntu/ctbs
          scp    -i ~/.ssh/id_rsa ../database/data_base.sql ubuntu@ec2-52-221-189-102.ap-southeast-1.compute.amazonaws.com:/home/ubuntu/ctbs
          scp    -i ~/.ssh/id_rsa ../database/data_many.sql ubuntu@ec2-52-221-189-102.ap-southeast-1.compute.amazonaws.com:/home/ubuntu/ctbs
          scp -r -i ~/.ssh/id_rsa ../frontend/integration ubuntu@ec2-52-221-189-102.ap-southeast-1.compute.amazonaws.com:/home/ubuntu/ctbs
          ssh    -i ~/.ssh/id_rsa ubuntu@ec2-52-221-189-102.ap-southeast-1.compute.amazonaws.com /home/ubuntu/ctbs/aws_push.sh
          ssh    -i ~/.ssh/id_rsa ubuntu@ec2-52-221-189-102.ap-southeast-1.compute.amazonaws.com /home/ubuntu/ctbs/aws_db.sh