name: Build and Release

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Install JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build with Maven
        working-directory: ./backend
        run: mvn -B package -Dmaven.test.skip --file pom.xml

        # Requires SECRETS_AWS from https://github.com/username/repo/settings/secrets/actions
        # The environment is called "Build Actions" which contains the two secrets. We need to specify this in our "env" section below.
        # ${{ secrets.AWS_PRIVATE_KEY }}
        # ${{ secrets.AWS_KNOWN_HOSTS }}
      - name: Connect to AWS and copy the JAR file to S3
        working-directory: ./backend
        shell: bash
        env: # use the environment from Build Actions
          SSH_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.AWS_KNOWN_HOSTS }}
        run: |
          set -x
          pwd
          mkdir -p ~/.ssh/
          printf %s\\n "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          printf %s\\n "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/id_rsa
          chmod 644 ~/.ssh/known_hosts
          ssh -i ~/.ssh/id_rsa ubuntu@ec2-52-221-189-102.ap-southeast-1.compute.amazonaws.com "printf \"%s\\n\" \"Actual write test: $(date)\" >> /home/ubuntu/testfile.txt"
          scp -i ~/.ssh/id_rsa target/backend-0.0.5-SNAPSHOT.jar ubuntu@ec2-52-221-189-102.ap-southeast-1.compute.amazonaws.com:/home/ubuntu/


