name: Run Spring Boot Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3

      - name: Install JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      # This step can be removed when database is hosted on a server.
      - name: Install Postgres and load data
        run: |
          docker run --name="pg" -u=postgres -e POSTGRES_PASSWORD="pg" -d --net=host cgr.dev/chainguard/postgres:latest
          sleep 5
          docker cp ./backend/src/main/resources/db/schema.sql   pg:/home/postgres
          docker cp ./backend/src/main/resources/db/trigger.sql  pg:/home/postgres
          docker cp ./backend/src/main/resources/db/data_base.sql     pg:/home/postgres
          docker cp ./backend/src/main/resources/db/data_many.sql     pg:/home/postgres
          docker exec pg psql -U postgres -f /home/postgres/schema.sql
          docker exec pg psql -U postgres -f /home/postgres/trigger.sql
          docker exec pg psql -U postgres -f /home/postgres/data_base.sql
          docker exec pg psql -U postgres -f /home/postgres/data_many.sql

      - name: Run Spring Boot Tests
        working-directory: ./backend
        run: mvn test --file pom.xml