name: Run Spring Boot Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3

      - name: Install JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Run Spring Boot Tests
        working-directory: ./backend/cinema-ticket-booking-system
        run: mvn test --file pom.xml
