name: Run Spring Boot Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3

      - name: Install JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Install Postgres on Docker and copy the database to it
        run: |
          docker run --name="pg" -u=postgres -e POSTGRES_PASSWORD="pg" -d --net=host cgr.dev/chainguard/postgres:latest
          sleep 5
          docker cp ./backend/src/main/resources/db/schema.sql   pg:/home/postgres
          docker cp ./backend/src/main/resources/db/trigger.sql  pg:/home/postgres
          docker cp ./backend/src/main/resources/db/data.sql     pg:/home/postgres
          docker exec pg psql -U postgres -f /home/postgres/schema.sql
          docker exec pg psql -U postgres -f /home/postgres/trigger.sql
          docker exec pg psql -U postgres -f /home/postgres/data.sql

      - name: Run Spring Boot Tests
        working-directory: ./backend
        run: mvn test --file pom.xml